version: '2'

volumes:
  pulse:                            # Only required if using PA over UNIX socket

services:

  # PulseAudio server
  audio:
    build: ./                       # See supported devices for other archs
    privileged: true
    labels:
      io.balena.features.dbus: 1    # Only required for bluetooth support
    ports:
      - 4317:4317                   # Only required if using PA over TCP socket
    volumes:
      - 'pulse:/run/pulse'          # Only required if using PA over UNIX socket

  # EXAMPLES SECTION
  # Bluetooth agent
  bluetooth:
    build: ./examples/bluetooth
    network_mode: host
    cap_add:
      - NET_ADMIN
    labels:
      io.balena.features.dbus: 1
  
  # SOX example using TCP socket
  sox:
    build: ./examples/sox
    
  # MPlayer example using UNIX socket
  mplayer:
    build: ./examples/mplayer
    volumes:
      - 'pulse:/run/pulse'
  
  # nodejs example using UNIX socket
  nodejs:
    build: ./examples/nodejs
    volumes:
      - 'pulse:/run/pulse'

  # alsa bridge example using UNIX socket
  alsa-bridge:
    build: ./examples/alsa-bridge
    volumes:
      - 'pulse:/run/pulse'